name: Keep Render Awake

on:
  schedule:
    - cron: '*/0.25 * * * *'  # Runs every 15 minutes (UTC time)
  workflow_dispatch:

jobs:
  keepalive:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render service
        run: curl -s https://resume-analyzer-hzrm.onrender.com > /dev/null
